# Generated by Django 5.1.7 on 2025-05-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsunit",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="news_images/"),
        ),
        migrations.AlterField(
            model_name="newsunit",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
