# Generated by Django 5.1.7 on 2025-05-14 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_newsreply"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsunit",
            options={
                "ordering": ["-pub_date"],
                "verbose_name": "新聞訊息",
                "verbose_name_plural": "新聞訊息",
            },
        ),
    ]
