# Generated by Django 5.1.7 on 2025-05-14 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_alter_newsunit_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsreply",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "新聞回覆",
                "verbose_name_plural": "新聞回覆",
            },
        ),
        migrations.AlterModelOptions(
            name="newsunit",
            options={},
        ),
    ]
