# Generated by Django 5.1.6 on 2025-05-14 17:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_alter_newsreply_options_alter_newsunit_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsreply",
            options={
                "ordering": ["created_at"],
                "verbose_name": "新聞回覆",
                "verbose_name_plural": "新聞回覆",
            },
        ),
    ]
